claritychallenge/clarity

clarity/data/scene_renderer_cec2.py

Fixed error in use of arctan2 when computing the head rotations

Fix rotation bug in scene_renderer_cec2.py

---

README.md
recipes/cpc1/README.md
recipes/cpc1/e032_sheffield/README.md

Update main README to add cpc1/e032_sheffield entry; fix errors in cpc1/README & cpc1/e032_sheffield/README

Update README files

---

README.md
recipes/cpc1/e029_sheffield/README.md
recipes/cpc1/e029_sheffield/config.yaml
recipes/cpc1/e029_sheffield/evaluate.py
recipes/cpc1/e029_sheffield/infer.py
recipes/cpc1/e029_sheffield/prepare_data.py
recipes/cpc1/e029_sheffield/train_asr.py
recipes/cpc1/e029_sheffield/transformer_cpc1.yaml
recipes/cpc1/e029_sheffield/transformer_cpc1_ensemble_decoder.py

Implementation of the CPC1 E029 Sheffield system.

cpc1 e029_sheffield

---

.gitignore
notebooks/Baseline_HASPI_scores.ipynb
notebooks/Installing_clarity_tools_and_using_metadata.ipynb

Resolves #13
This just adds the existing Notebooks to the repository so they are under version control and we can track changes to them. No modifications have been made to them and they still run.

13 | Adding notebooks to repository

---

.github/workflows/run_tests.yml
clarity/enhancer/compressor.py

The typehint " Tuple[Any, np.ndarray[Any, np.dtype[Any]], List[Any]]"
Was causing TypeError:
TypeError: 'numpy._DTypeMeta' object is not subscriptable
in Python 3.7.
Simplified to Tuple[Any, np.ndarray, List[Any]]

Fixed numpy typehint in compressor.py

---

.github/workflows/run_tests.yml
tests/evaluator/haaqi/test_haaqi.py
tests/evaluator/hasqi/test_hasqi.py

Using `pytest.aprox` and seven decimals.
These test result in the same value when running locally.
Signed-off-by: Gerardo Roa <gerardo.roa@gmail.com>

better regression test for hasqi and haaqi

---

.pylintrc
clarity/evaluator/mbstoi/mbstoi.py
clarity/evaluator/msbg/msbg.py
clarity/evaluator/msbg/msbg_utils.py
tests/regression/test_full_CEC1_pipeline.py

Giving the `msbg` evaluator the PEP8 treatment for variable/function/method/class names.
Realised I'd missed variables in a docstring for `mbstoi` evaluator, unsure what descriptions should be so if anyone can point me to explanations or knows what they should be that would be great, thanks.

98 | msbg evaluator nomenclature/PEP8 compliance; docstrings for mbstoi

---

.github/workflows/lint.yml
.github/workflows/run_tests.yml
.github/workflows/sphinx_docs_to_gh_pages.yaml

rsync from Makefile didn't appear to run, also performing as part of workflow prior to building docs.

126 | Moving recipes/**/README.md from workflow as well as Makefile

---

README.md

Just some trivial edits to the main README so that the repo landing page highlights the ICASSP challenge and the new HASQI and HAAQI tools.

Updated main README file for ICASSP release

---

clarity/__init__.py

Closes #149
Whilst #152 pulled in the automated publishing of this branch to PyPI the issue (#149) wasn't closed. On checking I appear to have left duplicated code in place, this PR tidies that up.

Tidying __init__.py

---

clarity/data/HOA_tools_cec2.py

Adds A-to-B conversion so that ICASSP recordings can be processed using clarity tools pipeline

Added a-to-b conversion in HOA_Tools_cec2.py

---

.github/workflows/run_tests.yml
.pre-commit-config.yaml
README.md

Adding local hook .pre-commit-config.yaml to run pylint

---

README.md

This is just an update to the top-level README file to highlight the CAD1 and CPC2 challenges.

190 main readme is out of date

---

recipes/cad1/README.md

Google Colab files were created and linked.

Added Jupyter Notebooks.

---

recipes/cad1/README.md
recipes/cad1/task1/baseline/README.md

This PR simply update the README files in CAD1 Task1 with the baseline results

229 add cad1 task1 baseline results

---

.pre-commit-config.yaml
clarity/data/utils.py

Changing pyupgrade argument to --py38-plus in commit hook and rerunning.

260-increase-pyupgrade-version

---

recipes/cad1/task1/baseline/enhance.py
tests/recipes/cad1/task1/test_enhance_task1.py

Fix an small index error in task 1

Indexing error in Task1

---

recipes/cad1/README.md
recipes/cad1/task1/baseline/README.md

This should complete the release of v0.3.1

 Adding the scores of Task1 after the fix - Cad1

---

clarity/utils/signal_processing.py
pyproject.toml
tests/utils/test_signal_processing.py

Improved version of the `signal_processing.resample` method that now supports multiple approaches.
**Note**: the PR will also change the default behaviour of the `file_io.read_signal` function so that resampling is performed with the `soxr` module with the high-quality setting. This matches the behaviour of `librosa.load`
Closes issue #309

Code and tests for extended resample method

---

README.md
recipes/cad_icassp_2024/baseline/README.md
recipes/cad_icassp_2024/baseline/config.yaml
recipes/cad_icassp_2024/generate_dataset/generate_at_mic_musdb18.py
tests/recipes/cad_icassp_2024/generate_dataset/test_generate_at_mic_musdb18.py

347 bug icassp 2024 is not generating all the data

---

notebooks/02_Running_the_CEC2_baseline_from_commandline.ipynb
notebooks/03_Running_the_CEC2_baseline_from_python.ipynb
recipes/cpc1/e029_sheffield/evaluate.py
recipes/cpc1/e029_sheffield/prepare_data.py
recipes/cpc1/e032_sheffield/evaluate.py
recipes/cpc1/e032_sheffield/prepare_data.py
tests/regression/test_enhancers.py

Fix format errors reported by pre-commit

---

clarity/enhancer/gha/gainrule_camfit.py

Change logging level in camfit code

---

recipes/cad2/task2/baseline/evaluate.py

This is a small fix for better evaluation script

Loading the segment for reference signal

---

clarity/evaluator/haspi/eb.py
clarity/utils/filterbanks.py
tests/evaluator/haspi/test_eb.py
tests/utils/test_filterbanks.py

Add new gammatones filters to #433

434 refractor gammatone filterbank

---

clarity/evaluator/msbg/cochlea.py
clarity/evaluator/msbg/msbg.py
clarity/utils/filterbanks.py
tests/evaluator/haspi/test_eb.py
tests/evaluator/msbg/test_cochlea.py
tests/evaluator/msbg/test_msbg.py

438 add smear param to msgb

---

README.md

Edits on main README to bring it up to date.

Updating main README.md page
