claritychallenge/clarity

- .pre-commit-config.yaml
check-yaml is not compatible with the hyperyaml files used in some recipes
> Removing check-yaml precommit hook

- docs/CODE_OF_CONDUCT.md
- docs/CONTRIBUTING.md
- docs/contributing.md
Resolves #17 
Adds `docs/CONTRIBUTING.md` guidelines and moves `CODE_OF_CONDUCT.md` to `docs/CODE_OF_CONDUCT.md`.
These will in due course be included automatically in the GitHub pages documentation (#16).
> Ns rse/17 contributing

- setup.cfg
This fix so that pytest-cov reports on all source files, not just those imported in tests.
> Fixed coverage config in setup.cfg

- clarity/enhancer/dnn/mc_conv_tasnet.py
The new PyTorch version 1.12.0 does not support four order input to conv1d in the SpatialEncoder, fix it by squeezing the redundant dimention.
> Fix mc_conv_tasnet version incompatible issue

- setup.cfg
This PR pulls in the quite minor changes made on branch `ns-rse/36-pypi` whilst testing releasing to PyPI to...
* include package data (`*.mat` and `*.yaml`).
* Ensure package name is `pyclarity` and version `0.1.0`.
* the modules under `recipe`.
It has been built and uploaded to PyPI and once merged to main the commit can be tagged with `v0.1.0`.
Prior to releasing I checked that the `ns-rse/36-pypi` branch that had been uploaded to TestPyPI could be installed in a clean Conda environment using...
```
❱ pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ pyclarity
```
...and then ran the three Notebooks. A little tweaking was required to some of the paths because where I started the Jupyter server differed from the location expected in the …
> 36 | Version and package name for release to PyPI; including recipes

- setup.cfg
workaround for issue https://gitlab.com/uweschmitt/pytest-regtest/-/issues/19
Signed-off-by: Gerardo Roa Dabike <gerardo.roa@gmail.com>
> add py as requirement for test

- recipes/cpc1/e029_sheffield/infer.py
- recipes/cpc1/e029_sheffield/transformer_cpc1.yaml
- recipes/cpc1/e029_sheffield/transformer_cpc1_ensemble_decoder.py
Pass the n_ensembles parameter to S2STransformerBeamSearch, so that multiple ASR models can be used (used to be just the first ASR model).
> Fix cpc1/e029 n_ensembles

- .pre-commit-config.yaml
- clarity/data/HOA_tools_cec2.py
- clarity/data/utils.py
- tests/conftest.py
- tests/data/test_HOA_tools_cec2.py
- tests/data/test_utils.py
Trying again as #88 was messy and confusing. Branched freshly from `main` and pulled over `tests/data/test_{utils,HOA_tools_cec2}.py` as well as `tests/conftest.py`, then added the `try: ... except: ...` statements I'd introduced to `clarity/data/utils.py` and `clarity/data/HOA_tools_cec2.py`.
All but two tests pass locally, the two that fail appear to be due to Torch trying to use my CPU and GPU (as mentioned in #97).
I've also made sure the `.pre-commit-config.yaml` uses up-to-date versions of each virtual environment (see [comment](https://github.com/claritychallenge/clarity/issues/97#issuecomment-1302254717)).
> Unittests for clarity/data/*.py; introduces tests/conftest.py

- .pre-commit-config.yaml
- .pylintrc
- clarity/evaluator/mbstoi/mbstoi.py
- clarity/evaluator/mbstoi/mbstoi_utils.py
- clarity/evaluator/mbstoi/parameters.yaml
- recipes/cec1/baseline/evaluate.py
- recipes/cpc1/baseline/run.py
First step in changing variable names to be more descriptive and "pythonic" (i.e. PEP8 compliant).
There are a few instances such as `for x...` where I have opted to disable the `pylint`/`flake8` check as they really don't make any difference.
I've tried to expand the docstrings too but there are still some gaps where I don't know what to write. 
Another perhaps unobvious change is that I've parameterised the values used in `mbstoi.py` such that they have defaults in the function but there is also a `parameters.yaml` which is loaded and used in the tests. This will allow future users to vary the values if desired. I'm not sure if that is something that would ever be likely to be done/needed but its good to have parameters with defaults rather than hard-coded variables.
Comments/feedback …
> Nomenclature PEP8 compliance

- .github/workflows/sphinx_docx_to_gh_pages.yaml
> 107 | Removing sphinx-markdown-tables patch from gh-pages build/deploy

- .pre-commit-config.yaml
Closes #110 
Updating the `repo:` target for `flake8` in the `.pre-commit-config.yaml`. At the same time I've updated all other `rev:` of the enabled repositories/hooks.
> 110 | Updating repo for flake8 in pre-commit; pre-commit autoupdate

- clarity/enhancer/dnn/mc_conv_tasnet.py
- clarity/enhancer/dsp/filter.py
- clarity/predictor/torch_msbg.py
- tests/regression/test_enhancers.py
- tests/regression/test_mc_conv_tasnet.py
- tests/regression/test_predictors.py
Closes #106 
Further to #101 this PR makes the `device` on which PyTorch tensors are run configurable across three modules.
Tests are then configured to explicitly use device "cpu" in the hope that it makes them configurable.
> 106 | Making device optional across modules and explicitly cpu in tests

- README.md
Signed-off-by: Gerardo Roa Dabike <gerardo.roa@gmail.com>
Closes #146 
PR is adding badges below the Clarity and Cadenza figures:
The current badges are:
* First row:
1. Last pip version
2. Python versions. The versions are obtained automatically, not sure yet how to specify a specific version like  ` 3.7 | 3.8 | 3.9 | 3.10`  Eg. like in https://github.com/asteroid-team/asteroid
3. Code style Black
4. Number of downloads
* Second Row
There are 2 badges that specify the pip version with the challenges. These are custom badges that we can change in colours and texts
Note, I didn't include this commit in @jonbarker68 Readme PR to avoid conflicts with that branch
> Adding Badges to Head of Readme

- .github/workflows/pypi.yaml
Closes #137
Uses the mentioned GitHub Action to attach the build artifacts (located under `build/`) to the release notes.
> Enhance workflow to attach build artifacts to Release Notes

- clarity/__init__.py
Closes #150
Very minor, but there was a redundant line floating around that this PR removes.
> Removing redundant and outdated manual version from __init__.py

- clarity/evaluator/haaqi/haaqi.py
- clarity/evaluator/haspi/ebm.py
Another step along the renaming path, this time for the `clarity.evaluator.haaqu.haaqi` sub-module.
A lot smaller this one!
> Haaqi PEP8 nomenclature

- .pre-commit-config.yaml
Previous version causes pre-commit checks to fail even if imports are sorted correctly
Closes #170
> Update isort pre-commit hook

- .git-blame-ignore-revs
- clarity/evaluator/haspi/eb.py
- clarity/evaluator/hasqi/__init__.py
- clarity/evaluator/hasqi/hasqi.py
- recipes/icassp_2023/baseline/evaluate.py
Giving Hasqi evaluator the PEP8 nomenclature treatment. Improved one function name in `eb` sub-module at the same time.
> Hasqi PEP8 nomenclature

- .pre-commit-config.yaml
- clarity/data/HOA_tools_cec2.py
- clarity/data/demo_data.py
- clarity/data/scene_builder_cec2.py
- clarity/data/scene_renderer_cec1.py
- clarity/data/utils.py
- tests/data/test_HOA_tools_cec2.py
Further work on PEP8 nomenclature, starting to address the `clarity/data/` modules.
* PEP8 nomenclature for some HOA_tools_cec2.py and improving some tests. Couldn't work out what some variables are though, happy to take feedback in this PR and update.
* Renaming a few variables and tidying up a bit in cec1.
* Docstrings in demo_data.py
* Also adding check_yaml to .pre-commit-config.yaml
* Docstrings and typing for scene_builder_cec2.py
> PEP8 nomenclature for some HOA_tools_cec2.py; improving some tests

- docs/CONTRIBUTING.md
Closes #243
Rewords the `Coding Style` section of `docs/CONTRIBUTING.md`
* Clarifying the Python linting tools used.
* Use of `pre-commit` and `pre-commit.ci`
* Preference to use `pathlib` over `os`
* Tweak to testing section.
I've purposefully not gone into too much depth covering all of the `pre-commit` hooks that are applied (e.g. Notebook linting and so forth) as I felt that would be overkill. The suggested changes hopefully are to the point and make contributors aware of the tools that are in place and they can dig into the details if they want/need to.
> Updating CONTRIBUTING.md

- pyproject.toml
I missed these out too and only just noticed.
> Align black and ruff target-version to py38 with rest of package

- clarity/data/scene_renderer_cec1.py
- clarity/enhancer/gha/gha_interface.py
- clarity/evaluator/msbg/msbg_utils.py
- clarity/utils/file_io.py
- clarity/utils/signal_processing.py
- recipes/cec1/baseline/evaluate.py
- recipes/cpc1/baseline/run.py
- recipes/cpc1/e029_sheffield/prepare_data.py
- recipes/cpc1/e032_sheffield/prepare_data.py
- tests/enhancer/gha/test_gha_interface.py
- tests/evaluator/msbg/test_msbg_utils.py
- tests/recipes/cec1/baseline/test_enhance.py
- tests/recipes/cec1/baseline/test_evaluate.py
- tests/recipes/cec1/data_preparation/test_prepare_cec1_data.py
- tests/recipes/cec1/e009_sheffield/test_test.py
- tests/recipes/cec2/baseline/test_enhance.py
- tests/recipes/cpc1/baseline/test_run.py
- tests/recipes/icassp_2023/baseline/test_enhance.py
- tests/recipes/icassp_2023/baseline/test_evaluate.py
- tests/regression/test_enhancers.py
- tests/utils/test_file_io.py
- tests/utils/test_signal_processing.py
Similar functions for reading and writing audio files were previously defined at several points in the library. These have all been replaced by a single pair of functions in utils/file_io that are better documented and provide consistent behaviour.
> 293-refactor-signal-read-and-write

- clarity/utils/file_io.py
- pyproject.toml
- tests/utils/test_file_io.py
When writing audio signals with PCM_16 there is a conversion from floating point with signals expected to be in the range [-1.0, 1.0). Where outside the range, signals currently silently overflow (unless the 'strict' option is set). 
This PR ensures values are clipped to the range -32768 to 32767 rather than being allowed to overflow. A warning is logged when this happens.
Closes issue #311
> Added clipping when writing audio in PCM_16 format

- recipes/cad1/README.md
- recipes/cad1/task2/baseline/README.md
- recipes/cad1/task2/baseline/evaluate.py
I found a typo in Recipe task 2 where the sample rate for the enhanced signal is passed incorrectly.
This originated when we reduced the sample rate of the submission to 32000 Hz
> For release 0.3.3

- .github/workflows/ORDA.yaml
- README.md
This should result in the artifacts of releases (`.zip` and `.tar.gz`) being uploaded directly to ORDA so they are linked to/traceable via a DOI.
I've also tweaked the PyPI v0.3.3 badge which was pointing v0.3.2.
> Adding ORDA workflow, tweaking README with badge

- recipes/cad1/task1/baseline/config.yaml
- recipes/cad1/task1/baseline/test.py
- recipes/cad1/task2/baseline/baseline_utils.py
- recipes/cad1/task2/baseline/config.yaml
- recipes/cad1/task2/baseline/test.py
Includes the code to run the evaluation and package the data for submission
Code for CAD1 - Task 1:
Code for CAD2 - Task 2:
Closes #334
> Code for evaluation in cad1 cpc2

- clarity/evaluator/msbg/smearing.py
- pyproject.toml
This should fix the problem that was causing some tests to fail with the newer numpy versions.
> Fixed smear3 to work with newer numpy versions

- pyproject.toml
- recipes/cec3/README.md
- recipes/cec3/baseline/enhance.py
- recipes/cec3/baseline/evaluate.py
The amplifier was appearing in the 'evaluate' stage, which was how things were done for ICASSP 2023 where teams were not expected to change it. It has now been moved into the 'enhance' stage so that it can be changed by the teams.
Note, this has not changed the scores. The enhance + evaluate still perform the same operations as before.
ie, enhance + (amplify + score) => (enhance + amplify) + score
> Fix to the CEC3 baseline recipes

- recipes/cad2/task1/baseline/config.yaml
- recipes/cad2/task1/baseline/evaluate.py
- recipes/cad2/task2/baseline/config.yaml
This PR brings changes in v0.6.1 to main branch
> Cad2 fix in main

- recipes/cad2/task1/baseline/config.yaml
- recipes/cad2/task1/baseline/evaluate.py
Whisper have a temperature parameter. By default, it uses several values that uses depending on the confident of the transcription. This can result in different transcription every time is run. 
We need to set this to a fix value so the evaluation is fair.
> set temperature to whisper
